version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/patent-db
      - JWT_SECRET=super_secret_key
      - PORT=5000
    depends_on:
      - mongodb
    volumes:
      - .:/app
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: