version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

  server:
    # Build uchun to'g'ri yo'lni ko'rsating
    build: ./server
    container_name: node-server
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - mongodb
    restart: always
    # Faqat ishlab chiqish uchun (development) volumes qo'shing.
    # Bu lokal kompyuterdagi fayllarni konteyner bilan sinxronlashtiradi.
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules # node_modules papkasini sinxronlashtirishdan istisno qilish uchun

volumes:
  mongodb_data: