version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always
    
    networks:
      - patent-network

  server:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: patent-server
    ports:
      - "5000:5000"
    env_file: .env
    environment:
      - MONGO_URI=mongodb://mongodb:27017/patent-db
      - JWT_SECRET=your_jwt_secret
      - PORT=5000
      - NODE_ENV=development
    depends_on:
      - mongodb
    volumes:
      - ./:/app
      - /app/node_modules
    restart: always
    networks:
      - patent-network
    # Debug uchun komanda
    command: >
      sh -c "
        echo 'Server ishga tushirilmoqda...' &&
        node -e \"console.log('Environment:', process.env)\" &&
        node index.js
      "

networks:
  patent-network:
    driver: bridge

volumes:
  mongodb_data: