version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

  server:
    # Ehtimol, sizning ishlagan versiyangizda build yo'li `./server` bo'lgan
    build: ./server
    container_name: node-server
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - mongodb
    restart: always

volumes:
  mongodb_data: